### ISSUE TITLE
Different thrust coefficient for blackbird dataset

### ISSUE THREAD

**Issue by juanmed** [uzh-rpg/vimo#4]
Hi,

Looking at your code for vertical rotor thrust calculation in [Line 339](https://github.com/uzh-rpg/vimo/blob/cf6b19e72b437476415a8208fa22f7b75303ee7a/vimo_estimator/src/estimator_node.cpp#L339), I see a slight difference in the  thrust coefficient for the rotors: you set it as `2.03e-8` while blackbird dataset authors indicate `2.27e-8`. Is there any reason behind this?

Thanks,

**Comment by foehnx** [comment]
To the best of my knowledge, this value was adapted to replicate exact gravity compensation in hover, since otherwise a constant force in body-z direction would be estimated.
