### ISSUE TITLE
catkin_make error 

### ISSUE THREAD

**Issue by fishpp-qq** [uzh-rpg/vimo#6]
catkin_make has a problem as follows:
/home/shraouqiu/VIMO_WS/src/vimo/vimo_estimator/src/estimator.h:13:10: fatal error: blackbird/MotorRPM.h: No such file or directory
 #include <blackbird/MotorRPM.h>

**Comment by foehnx** [comment]
It seems that your question has been answered in

https://github.com/uzh-rpg/vimo/issues/1#issuecomment-834625170

and

https://github.com/uzh-rpg/vimo/issues/1#issuecomment-834633455

Therefore I think this can be closed, right?
